### ISSUE TITLE
Roadmap or to-do list

### ISSUE THREAD

**Issue by bartosjiri** [ParallelGarden/Hydroponics-in-a-box#1]
Any plans for creating a roadmap or to-do list for the project? I would love to contribute, however, some specific directions and goals are needed for that first. Is there any vision for it or do you leave it completely open?

**Comment by jhamat1** [comment]
We are finalizing the documentation...sorry for the inconvenience...it's our first open source project, and we are still learning. We will definitely keep uploading more materials, at first we will focus on the read me file to explain background and purpose of the project, and to outline visions for development. So far I'm sure we will be testing lights, organic fertilizers and organic substrates - in these areas we appreciate any feedback any time. Also we are planning to publish the IoT project of our colleagues who already implemented their initial version of the device at our box to publish complete HW and SW technologies. Thank you for your suggestion, we'll keep working on it ;)
